name: Build Wasm



on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v7
      with:
          version: "latest" #"1.39.15"

    - name: Verify Emscripten
      run: emcc -v
        
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Build wasm
      env: 
        BUILD_TARGET_NAME: PopMondegreen
      run: PopMondegreen.Emscripten/Build.sh PopMondegreen.Emscripten/ release
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PopMondegreen.Wasm
        path: PopMondegreen.Emscripten/Build
