name: Build Macos Static


on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - '*Test*'
      - '*orkflow*'

jobs:
  Build:
    name: Macos Static Library
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build Macos Static
        uses: NewChromantics/PopAction_BuildApple@v1.0.11
        with:
          BuildScheme: PopMondegreen_MacosStatic
          project: PopMondegreen

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          # tsdk: these env vars are set in each of the actions
          name: ${{ env.UPLOAD_NAME }}
          path: ${{ env.UPLOAD_DIR }}
          if-no-files-found: error
